# -*- coding: utf-8 -*-
"""02 aula_funcoes_bibliotecas_lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yUkU4wL9Hm4WKD5SSMetoUCg6VYdEP_W

# Aula Teórico-Prática: Funções e Bibliotecas em Python

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Objetivo da aula

Apresentar os conceitos fundamentais para a criação e utilização de funções em Python, incluindo funções `lambda`, validação de parâmetros e utilização de bibliotecas simples.

</div>

---

## Conteúdos principais

| Área | Conteúdos |
|---|---|
| **Funções** | Criação com `def`, chamada de funções, parâmetros e argumentos |
| **Procedimentos e funções** | Diferença entre executar uma ação com `print()` e devolver um valor com `return` |
| **Validação** | Verificação dos dados recebidos por uma função |
| **Mutabilidade** | Objetos mutáveis e imutáveis em Python |
| **Lambda** | Criação de funções curtas e aplicação com `map()` e `filter()` |
| **Bibliotecas** | Importação e utilização de `math`, `random` e `datetime` |

---

## Estrutura da sessão

| Momento | Descrição |
|---|---|
| **1. Conceitos essenciais** | Apresentação dos principais conceitos teóricos |
| **2. Demonstrações em Python** | Execução de exemplos simples no Google Colab |

# 1. Introdução às funções



---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Uma função é um bloco de código reutilizável que ajuda a organizar o programa, evitar repetição e executar uma tarefa sempre que necessário.

</div>

---

## Para que servem?

| Utilidade | Explicação |
|---|---|
| **Evitar repetição** | Reutilizam o mesmo código várias vezes |
| **Organizar o programa** | Dividem o código em partes mais simples |
| **Melhorar a leitura** | Tornam o código mais claro |
| **Facilitar alterações** | Permitem alterar uma tarefa num único local |

---

## Definir e chamar uma função

Uma função tem três partes importantes:

| Parte | Significado |
|---|---|
| **Definição** | Criação da função com `def` |
| **Corpo da função** | Instruções indentadas que pertencem à função |
| **Chamada** | Execução da função pelo seu nome |

```python
def mostrar_mensagem():
    print("Bem-vindo à aula de Python!")

mostrar_mensagem()
```

Neste exemplo, `def mostrar_mensagem():` define a função e `mostrar_mensagem()` chama a função.

---

## A ordem importa?

Sim. Em Python, o código é executado de cima para baixo.  
Por isso, a função deve estar definida antes de ser chamada durante a execução.

| Situação | Resultado |
|---|---|
| Definir antes de chamar | Correto |
| Chamar antes de definir | Erro |

---

## Nota

Em Python, as funções são criadas com a palavra-chave `def`.

As células seguintes mostram um exemplo sem função e depois o mesmo exemplo usando uma função.
"""

# Exemplo simples sem função

print("Bem-vindo à aula de Python!")
print("Bem-vindo à aula de Python!")
print("Bem-vindo à aula de Python!")

# O mesmo exemplo usando uma função

def mostrar_mensagem():
    print("Bem-vindo à aula de Python!")

mostrar_mensagem()
mostrar_mensagem()
mostrar_mensagem()

"""# 2. Objetos mutáveis e imutáveis em Python

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Em Python, os valores são objetos. Algumas variáveis podem referenciar o mesmo objeto, mas o comportamento depende de esse objeto ser mutável ou imutável.

</div>

---

## Tipos de objetos

| Tipo | Explicação | Exemplos |
|---|---|---|
| **Imutável** | Não pode ser alterado diretamente depois de criado | `int`, `float`, `str`, `bool`, `tuple` |
| **Mutável** | Pode ser alterado depois de criado | `list`, `dict`, `set` |

---

## Porque é importante?

Esta distinção é relevante quando os objetos são atribuídos a variáveis ou passados para funções.

| Tipo de objeto | Comportamento geral |
|---|---|
| **Imutável** | A alteração faz a variável referenciar outro objeto |
| **Mutável** | O conteúdo do próprio objeto pode ser alterado |

---

## Demonstração

As células seguintes mostram:

1. um exemplo com um objeto imutável;
2. um exemplo com um objeto mutável.

"""

# Exemplo de objeto imutável
# Os inteiros são imutáveis: o valor 10 não é alterado diretamente.

print("=== Objeto imutável ===")
print()

numero = 10
mesmo_numero = numero

print("Valor inicial através de numero:", numero)
print("Valor inicial através de mesmo_numero:", mesmo_numero)

print()

# numero passa a referenciar um novo objeto com o valor 11.
# mesmo_numero continua a referenciar o valor 10.

numero = numero + 1

print("Depois de fazer numero = numero + 1:")
print("numero:", numero)
print("mesmo_numero:", mesmo_numero)

print()

# mesmo_numero passa a referenciar um novo objeto com o valor 15.
# numero continua a referenciar o valor 11.

mesmo_numero = mesmo_numero + 5

print("Depois de fazer mesmo_numero = mesmo_numero + 5:")
print("numero:", numero)
print("mesmo_numero:", mesmo_numero)

print()

# Conclusão:
# Como os inteiros são imutáveis, cada alteração cria/obtém um novo objeto.
# Cada variável pode passar a referenciar um objeto diferente.

# Exemplo de objeto mutável
# As listas são objetos mutáveis: podem ser modificadas depois de criadas.

print("=== Objeto mutável ===")
print()

nomes = ["Ana", "João"]
mesma_lista = nomes

print("Lista inicial através de nomes:", nomes)
print("Lista inicial através de mesma_lista:", mesma_lista)

print()

mesma_lista.append("Maria")

print("Depois de adicionar 'Maria' com mesma_lista:")
print("nomes:", nomes)
print("mesma_lista:", mesma_lista)

print()

nomes.append("Pedro")

print("Depois de adicionar 'Pedro' com nomes:")
print("nomes:", nomes)
print("mesma_lista:", mesma_lista)

print()

# Conclusão:
# nomes e mesma_lista são duas variáveis diferentes,
# mas referenciam o mesmo objeto em memória.
# Como a lista é mutável, a alteração feita através de uma variável
# aparece também através da outra.

"""# 3. Criar funções com `def`

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Em Python, uma função é criada com `def` e o código que pertence à função é identificado pela indentação.

</div>

---

## Estrutura geral

```python
def nome_da_funcao():
    instrucao_dentro_da_funcao

instrucao_fora_da_funcao
```

---

## Elementos principais

| Elemento | Significado |
|---|---|
| `def` | Indica que vamos criar uma função |
| `nome_da_funcao` | Nome escolhido para a função |
| `()` | Local onde podem existir parâmetros |
| `:` | Marca o início do bloco da função |
| **Indentação** | Indica o código que pertence à função |
| **Fim da indentação** | Indica que o código seguinte já está fora da função |

---

## Exemplo

```python
def mostrar_mensagem():
    print("Esta linha está dentro da função.")

print("Esta linha está fora da função.")
```

Neste exemplo:

- a linha indentada pertence à função;
- a linha sem indentação já está fora da função;
- definir a função não a executa automaticamente.

"""

# Criar uma função simples

def mostrar_boas_vindas():
    print("Esta linha está dentro da função.")

print("Esta linha está fora da função.")

mostrar_boas_vindas()

"""# 4. Chamar uma função

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Criar uma função não significa executá-la. Para executar uma função, é necessário chamá-la pelo seu nome.

</div>

---

## Chamada de função

```python
mostrar_boas_vindas()
```

A mesma função pode ser chamada várias vezes.

"""

# Chamar a função várias vezes

mostrar_boas_vindas()
mostrar_boas_vindas()
mostrar_boas_vindas()

"""# 5. Procedimentos vs funções em Python

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Em Python, as funções são sempre criadas com `def`, mas podem ser usadas para executar uma ação ou para devolver um valor.

</div>

---

## Dois usos possíveis

| Utilização | O que faz | Resultado |
|---|---|---|
| **Procedimento** | Executa uma ação | Normalmente mostra informação com `print()` |
| **Função** | Calcula ou processa dados | Devolve um valor com `return` |

---

## Diferença essencial

| Conceito | Explicação |
|---|---|
| **Procedimento** | Realiza uma ação, mas não devolve um valor útil para ser reutilizado |
| **Função** | Devolve um resultado que pode ser guardado, reutilizado ou usado noutro cálculo |

# 6. `print()` vs `return`

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

`print()` mostra informação no ecrã. `return` devolve um valor ao programa.

</div>

---

## Diferença principal

| Comando | O que faz | Utilização típica |
|---|---|---|
| `print()` | Mostra informação no ecrã | Apresentar resultados ao utilizador |
| `return` | Devolve informação ao programa | Guardar, reutilizar ou processar resultados |

---

## Exemplo conceptual

O factorial de `n` é calculado multiplicando os números de `1` até `n`.

```text
5! = 5 × 4 × 3 × 2 × 1 = 120
```

```python
def mostrar_factorial(n):
    # calcular o factorial
    resultado = ...
    print(resultado)

def calcular_factorial(n):
    # calcular o factorial
    resultado = ...
    return resultado
```

| Exemplo | Objetivo |
|---|---|
| `mostrar_factorial(n)` | Calcula e mostra o resultado com `print()` |
| `calcular_factorial(n)` | Calcula e devolve o resultado com `return` |

---

## Nota importante

Uma função sem `return` devolve automaticamente `None`.  
Quando se pretende reutilizar um resultado, deve ser usado `return`.

# 7. Exemplo utilizado: factorial de um número

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

O factorial será usado para demonstrar a diferença entre um procedimento com `print()` e uma função com `return`.

</div>

---

## Factorial

O factorial de um número inteiro não negativo `n` representa-se por `n!`.

```text
n! = n × (n - 1) × (n - 2) × ... × 1
```

Exemplo:

```text
5! = 5 × 4 × 3 × 2 × 1 = 120
```

Nesta aula, o foco está no uso da função, não no detalhe do cálculo matemático.
"""

# Exemplo de procedimento
# Este procedimento calcula o factorial e mostra o resultado no ecrã.
# Como não usa return, não devolve um valor útil ao programa.

def mostrar_factorial(n):
    resultado = 1

    for i in range(1, n + 1):
        resultado = resultado * i

    print("O factorial de", n, "é", resultado)

valor = mostrar_factorial(5)

print("Valor guardado na variável:", valor)

# Exemplo de função
# Esta função calcula o factorial e devolve o resultado com return.
# Como usa return, o valor pode ser guardado e reutilizado.

def calcular_factorial(n):
    resultado = 1

    for i in range(1, n + 1):
        resultado = resultado * i

    return resultado

valor = calcular_factorial(5)

print("Valor guardado na variável:", valor)

"""# 8. Reutilizar o valor devolvido

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Quando uma função usa `return`, o valor devolvido pode ser guardado numa variável e reutilizado noutros cálculos.

</div>

---

## Exemplo

No exemplo seguinte, o factorial é calculado uma vez e depois reutilizado para calcular outros valores.

"""

# Reutilizar o valor devolvido pela função

valor = calcular_factorial(5)

dobro = valor * 2
soma = valor + 10

print("Factorial:", valor)
print("Dobro do factorial:", dobro)
print("Factorial somado a 10:", soma)

"""# 9. Parâmetros e argumentos

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

As funções podem receber valores. Esses valores tornam a função mais flexível, porque permitem executar a mesma tarefa com dados diferentes.

</div>

---

## Diferença entre parâmetro e argumento

| Conceito | Explicação | Exemplo |
|---|---|---|
| **Parâmetro** | Nome usado na definição da função | `n` em `def calcular_factorial(n):` |
| **Argumento** | Valor passado quando a função é chamada | `5` em `calcular_factorial(5)` |

---

## Exemplo

```python
def calcular_factorial(n):
    # código da função
    return resultado

calcular_factorial(5)
```

Neste exemplo:

- `n` é o **parâmetro**;
- `5` é o **argumento**;
- a função pode ser chamada com outros argumentos, como `3`, `4` ou `6`.

---

## Nota

O parâmetro funciona como uma variável local dentro da função.

"""

# O parâmetro é n.
# O argumento é o valor passado quando a função é chamada.

print("Factorial de 3:", calcular_factorial(3))
print("Factorial de 5:", calcular_factorial(5))
print("Factorial de 7:", calcular_factorial(7))

"""# 10. Validação de parâmetros e tratamento de erros

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Uma função deve verificar se recebeu valores válidos antes de executar o cálculo. Quando recebe valores inválidos, pode lançar uma exceção para sinalizar o erro.

</div>

---

## Porque validar parâmetros?

A validação ajuda a:

| Objetivo | Explicação |
|---|---|
| **Evitar erros** | Impede que a função execute cálculos com dados inadequados |
| **Tornar o código mais seguro** | Reduz comportamentos inesperados |
| **Melhorar a clareza** | Indica claramente quais os valores aceites pela função |

---

## Regras para o factorial

No caso do factorial, vamos aplicar duas regras:

| Regra | Exemplo válido | Exemplo inválido | Exceção adequada |
|---|---|---|---|
| O valor deve ser inteiro | `5` | `2.5`, `"João"` | `TypeError` |
| O valor deve ser maior ou igual a zero | `0`, `5` | `-3` | `ValueError` |

---

## Momentos importantes

| Momento | O que acontece |
|---|---|
| **1. Validação dos dados** | A função usa `if` para verificar se os dados recebidos são válidos |
| **2. Tratamento simples do erro** | A função pode devolver uma mensagem de erro com `return` |
| **3. Lançamento de exceção** | A função pode sinalizar o erro com `raise`, usando exceções como `TypeError` ou `ValueError` |
| **4. Chamada sem tratamento** | Se a função lançar uma exceção e não houver `try` / `except`, o erro aparece diretamente no Colab |
| **5. Chamada com tratamento** | O erro é capturado com `try` / `except` e apresentado de forma controlada |

---

## Exemplo conceptual

Existem várias formas de lidar com valores inválidos dentro de uma função.

---

### 1. Validação simples

A função verifica o erro e devolve uma mensagem.

```python
def calcular_factorial(n):

    if n não for inteiro:
        return "Erro: o valor deve ser um número inteiro."

    if n for menor que zero:
        return "Erro: o número deve ser maior ou igual a zero."

    calcular factorial

    return resultado
```

Nesta abordagem, a função não interrompe o programa, mas pode devolver tipos diferentes de resultado: por exemplo, um número quando corre bem e uma mensagem quando corre mal.

---

### 2. Validação com exceções

A função verifica o erro e lança uma exceção.

```python
def calcular_factorial(n):

    if n não for inteiro:
        raise TypeError("O valor deve ser um número inteiro.")

    if n for menor que zero:
        raise ValueError("O número deve ser maior ou igual a zero.")

    calcular factorial

    return resultado
```

Nesta abordagem, a função devolve o resultado apenas quando os dados são válidos. Quando existe erro, sinaliza o problema com uma exceção.

---

## Comparação

| Abordagem | Como sinaliza o erro | Vantagem | Limitação |
|---|---|---|---|
| **Validação simples** | `return "Erro..."` | Fácil de perceber | Mistura resultados com mensagens de erro |
| **Validação com exceções** | `raise TypeError` ou `raise ValueError` | Mais correta e profissional | Exige compreender `try` / `except` |

---

## Ideia-chave

O `if` serve para verificar a condição.  
Depois, a função pode lidar com o erro de duas formas:

- devolver uma mensagem simples com `return`;
- lançar uma exceção com `raise`.

"""

## 1. Validação simples com return
### A função deteta o erro e devolve uma mensagem.
### Esta abordagem é simples, mas mistura números com mensagens de erro.

def calcular_factorial(n):
    if type(n) != int:
        return "Erro: o valor deve ser um número inteiro."

    if n < 0:
        return "Erro: o número deve ser maior ou igual a zero."

    resultado = 1

    for i in range(1, n + 1):
        resultado = resultado * i

    return resultado


valor = 5
resultado = calcular_factorial(valor)
print("Resultado para", valor, ":\t", resultado)

valor = -3
resultado = calcular_factorial(valor)
print("Resultado para", valor, ":\t", resultado)

valor = 2.5
resultado = calcular_factorial(valor)
print("Resultado para", valor, ":\t", resultado)

## 2. Validação com raise
### A função deteta o erro e lança uma exceção.
### Esta abordagem é mais profissional.

def calcular_factorial(n):
    if type(n) != int:
        raise TypeError("O valor deve ser um número inteiro.")

    if n < 0:
        raise ValueError("O número deve ser maior ou igual a zero.")

    resultado = 1

    for i in range(1, n + 1):
        resultado = resultado * i

    return resultado


valor = 5
resultado = calcular_factorial(valor)
print("Factorial de", valor, ":\t", resultado)

valor = -3
resultado = calcular_factorial(valor)
print("Factorial de", valor, ":\t", resultado)

valor = 2.5
resultado = calcular_factorial(valor)
print("Factorial de", valor, ":\t", resultado)

# 3. Chamada com tratamento da exceção
# O try tenta executar a função.
# O except trata o erro caso ele ocorra.

def calcular_factorial(n):
    if type(n) != int:
        raise TypeError("O valor deve ser um número inteiro.")

    if n < 0:
        raise ValueError("O número deve ser maior ou igual a zero.")

    resultado = 1

    for i in range(1, n + 1):
        resultado = resultado * i

    return resultado


valores_teste = [5, -3, 2.5]

for valor in valores_teste:
    try:
        resultado = calcular_factorial(valor)
        print("Factorial de", valor, ":\t", resultado)

    except ValueError as erro:
        print("Erro de valor para", valor, ":\t", erro)

    except TypeError as erro:
        print("Erro de tipo para", valor, ":\t", erro)

"""# 11. Impacto dos objetos mutáveis e imutáveis nas funções

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Quando um objeto é passado para uma função, o comportamento pode ser diferente consoante esse objeto seja mutável ou imutável.

</div>

---

## Comportamento geral

| Tipo de objeto | Exemplos | Comportamento dentro da função |
|---|---|---|
| **Imutável** | `int`, `float`, `str`, `bool`, `tuple` | A função não altera diretamente o objeto original |
| **Mutável** | `list`, `dict`, `set` | A função pode alterar o conteúdo do objeto original |

---

## Porque é importante?

Esta distinção ajuda a evitar alterações inesperadas.

| Situação | Resultado possível |
|---|---|
| Passar um número para uma função | O valor original fora da função não é alterado diretamente |
| Passar uma lista para uma função | A lista original pode ser modificada dentro da função |

---

## Nota

Ao trabalhar com objetos mutáveis, como listas ou dicionários, é importante ter cuidado com alterações feitas dentro das funções.

As células seguintes mostram esta diferença com exemplos simples.

"""

# Exemplo com objeto imutável
# Os inteiros são imutáveis.
# A variável x recebe a referência ao mesmo valor que numero.
# Quando fazemos x = x + 1, x passa a referenciar um novo objeto.
# A variável numero, fora da função, continua igual.

def alterar_numero(x):
    print("Dentro da função, antes da alteração:", x)

    x = x + 1

    print("Dentro da função, depois da alteração:", x)

numero = 10

print("Fora da função, antes da chamada:", numero)

alterar_numero(numero)

print("Fora da função, depois da chamada:", numero)

# Exemplo com objeto mutável
# As listas são mutáveis.
# A variável lista recebe a referência à mesma lista que nomes.
# Quando fazemos lista.append("Maria"), a lista original é alterada.
# Por isso, a alteração também é visível fora da função.

def adicionar_nome(lista):
    print("Dentro da função, antes da alteração:", lista)

    lista.append("Maria")

    print("Dentro da função, depois da alteração:", lista)

nomes = ["Ana", "João"]

print("Fora da função, antes da chamada:", nomes)

adicionar_nome(nomes)

print("Fora da função, depois da chamada:", nomes)

"""# 12. Boas práticas na criação de funções

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Uma boa função deve ter um objetivo claro, um nome compreensível e uma única responsabilidade principal.

</div>

---

## Recomendações principais

| Boa prática | Explicação |
|---|---|
| **Usar nomes claros** | O nome da função deve indicar a tarefa que a função realiza |
| **Aplicar o Princípio da Responsabilidade Única** | Cada função deve ter uma responsabilidade principal e resolver uma tarefa bem definida |
| **Manter a função simples** | A função deve ser fácil de ler, testar e corrigir |
| **Evitar repetição** | Código repetido pode ser colocado numa função reutilizável |
| **Validar parâmetros** | A função deve verificar os dados recebidos quando existe risco de valores inválidos |
| **Evitar efeitos inesperados** | Objetos mutáveis, como listas, devem ser alterados com cuidado |
| **Usar `return` quando necessário** | Se o resultado tiver de ser reutilizado, deve ser devolvido com `return` |

---

## Princípio da Responsabilidade Única

Uma função deve fazer **uma tarefa principal** e fazê-la bem.

Exemplo adequado:

```python
def calcular_factorial(n):
    return resultado
```

Exemplo menos adequado:

```python
def calcular_factorial_mostrar_e_guardar(n):
    # calcula o factorial
    # mostra o resultado
    # guarda o resultado noutro local
```

Neste segundo caso, a função acumula várias responsabilidades.

---

## Exemplo de nomes

| Nome | Avaliação | Motivo |
|---|---|---|
| `calcular_factorial()` | Adequado | Indica claramente o que a função faz |
| `cf()` | Pouco claro | É demasiado abreviado e pouco informativo |

---

## Regra prática

Ao ler o nome da função, deve ser possível perceber a sua finalidade principal.

"""

# Exemplo de função com nome claro

def calcular_quadrado(numero):
    return numero * numero

resultado = calcular_quadrado(4)

print("Quadrado:", resultado)

"""## Nota: funções recursivas

Uma função recursiva é uma função que se chama a si própria.

Exemplo simples com factorial:

```python
def factorial_recursivo(n):
    if n == 0:
        return 1
    return n * factorial_recursivo(n - 1)
```

Nesta aula, a recursividade é apenas referida como possibilidade. O foco principal continua a ser funções simples, `lambda` e bibliotecas.

# 13. Funções `lambda`

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Uma função `lambda` é uma função curta, anónima e escrita normalmente numa única linha.

</div>

---

## Estrutura geral

```python
lambda argumentos: expressão
```

---

## Exemplo simples

```python
lambda x: x * 2
```

Neste exemplo:

| Elemento | Significado |
|---|---|
| `lambda` | Indica que está a ser criada uma função anónima |
| `x` | Valor recebido pela função |
| `x * 2` | Expressão devolvida pela função |

---

## Quando usar?

| Situação | Exemplo |
|---|---|
| **Operações simples** | Multiplicar um valor por 2 |
| **Funções curtas** | Expressões que cabem numa linha |
| **Uso temporário** | Aplicação com `map()` ou `filter()` |

---

## Nota

Funções `lambda` devem ser usadas apenas quando tornam o código simples e legível. Para funções mais complexas, deve ser usada uma função normal com `def`.
"""

# Lambda simples

dobro = lambda x: x * 2

print(dobro(5))

"""# 14. Aplicar `lambda` a listas com `map()` e `filter()`

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Uma função `lambda` pode ser usada para definir uma operação simples. Com `map()` e `filter()`, essa operação pode ser aplicada aos elementos de uma lista.

</div>

---

## Dois usos comuns

| Função | Para que serve | Exemplo |
|---|---|---|
| `map()` | Transforma todos os elementos de uma lista | Multiplicar todos os números por `2` |
| `filter()` | Seleciona apenas os elementos que cumprem uma condição | Selecionar apenas números pares |

---

## Exemplo com `map()`

```python
numeros = [1, 2, 3, 4, 5]

dobros = list(map(lambda x: x * 2, numeros))
```

Neste exemplo:

| Parte | Significado |
|---|---|
| `lambda x: x * 2` | Define a transformação: multiplicar cada valor por `2` |
| `map(...)` | Aplica essa transformação a todos os elementos |
| `list(...)` | Converte o resultado numa lista visível |

Resultado esperado:

```python
[2, 4, 6, 8, 10]
```

---

## Exemplo com `filter()`

```python
numeros = [1, 2, 3, 4, 5, 6]

pares = list(filter(lambda x: x % 2 == 0, numeros))
```

Neste exemplo:

| Parte | Significado |
|---|---|
| `lambda x: x % 2 == 0` | Define a condição: verificar se o número é par |
| `filter(...)` | Mantém apenas os elementos que cumprem a condição |
| `list(...)` | Converte o resultado numa lista visível |

Resultado esperado:

```python
[2, 4, 6]
```

---

## Nota sobre programação funcional

O uso de `lambda` com funções como `map()` e `filter()` está associado à **programação funcional**.

Neste estilo, uma função pode ser passada como argumento para outra função.

| Conceito | Exemplo |
|---|---|
| **Função anónima** | `lambda x: x * 2` |
| **Função de ordem superior** | `map()` e `filter()` recebem uma função como argumento |
| **Programação funcional** | Uso de funções para transformar ou filtrar dados |

---

## Onde este estilo é útil?

Este tipo de programação é útil quando se pretende aplicar a mesma regra a vários dados.

| Área | Utilidade |
|---|---|
| **Tratamento de dados** | Transformar, limpar ou filtrar listas de valores |
| **Análise de dados** | Selecionar dados que cumprem determinada condição |
| **Automatização** | Aplicar rapidamente uma regra a vários elementos |
| **Big Data** | Aplicar operações semelhantes a grandes volumes de dados, usando ferramentas próprias |

Em contextos de **Big Data**, a ideia de transformar e filtrar dados é muito comum em ferramentas como Apache Spark.  
Nesta aula, os exemplos são simples, mas a lógica é semelhante: definir uma regra e aplicá-la a vários elementos.

---

## Nota final

Nesta aula, estes conceitos são usados apenas de forma introdutória.

"""

# Exemplo com map()
# Multiplicar todos os valores da lista por 2

numeros = [1, 2, 3, 4, 5]

dobros = list(map(lambda x: x * 2, numeros))

print("Lista original:", numeros)
print("Lista com valores a dobrar:", dobros)

# Exemplo com filter()
# Selecionar apenas os números pares da lista

numeros = [1, 2, 3, 4, 5, 6]

pares = list(filter(lambda x: x % 2 == 0, numeros))

print("Lista original:", numeros)
print("Números pares:", pares)

"""# 15. Diferença entre `def` e `lambda`

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Tanto `def` como `lambda` permitem criar funções, mas são usados em contextos diferentes.

</div>

---

## Comparação principal

| Aspeto | `def` | `lambda` |
|---|---|---|
| **Uso principal** | Funções normais e reutilizáveis | Funções curtas e pontuais |
| **Tamanho** | Pode ter várias instruções | Tem apenas uma expressão |
| **Nome** | Normalmente tem um nome definido | Pode ser anónima |
| **Legibilidade** | Melhor para funções maiores | Melhor para operações simples |
| **Exemplo típico** | Calcular factorial com várias instruções | Multiplicar um valor por `2` |

---

## Exemplo conceptual

```python
def dobrar(x):
    return x * 2

lambda x: x * 2
```

Ambas podem representar a mesma operação simples: devolver o dobro de um valor.

---

## Regra prática

| Situação | Recomendação |
|---|---|
| A função tem várias instruções | Usar `def` |
| A função precisa de validação | Usar `def` |
| A função será reutilizada várias vezes | Usar `def` |
| A operação é curta e simples | Pode ser usada `lambda` |
| A função é usada temporariamente com `map()` ou `filter()` | Pode ser usada `lambda` |

---

## Nota

Para código mais claro e fácil de manter, deve ser usada `lambda` apenas quando a expressão é simples e facilmente compreensível.

"""

# Versão com def

def dobrar(x):
    return x * 2

numeros = [1, 2, 3, 4, 5]

dobros = list(map(dobrar, numeros))

print(dobros)

# Versão com lambda

numeros = [1, 2, 3, 4, 5]

dobros = list(map(lambda x: x * 2, numeros))

print(dobros)

"""-------------

# 1. Introdução às bibliotecas em Python

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Uma biblioteca é um conjunto de código já criado que pode ser reutilizado num programa.

</div>

---

## Exemplos de bibliotecas internas

| Biblioteca | Utilidade |
|---|---|
| `math` | Operações matemáticas |
| `random` | Geração de valores aleatórios |
| `datetime` | Trabalho com datas e horas |

---

## Vantagens

- Poupar tempo;
- evitar escrever tudo do zero;
- usar funcionalidades já existentes;
- tornar os programas mais completos.

# 2. Formas de importar bibliotecas

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Antes de usar uma biblioteca, é necessário importá-la para o programa.

</div>

---

## Formas comuns de importação

| Forma | Exemplo | Utilização |
|---|---|---|
| Importar biblioteca completa | `import math` | Usar funções com `math.nome_da_funcao()` |
| Importar uma função específica | `from math import sqrt` | Usar diretamente `sqrt()` |
| Usar alias | `import random as rd` | Criar um nome abreviado para a biblioteca |
# New section
"""

# Importar a biblioteca completa

import math

print(math.sqrt(25))
print(math.pi)

# Importar apenas uma função

from math import sqrt

print(sqrt(36))

# Importar com nome abreviado

import random as rd

numero = rd.randint(1, 10)

print(numero)

"""# 3. Funções com bibliotecas

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

Também é possível criar funções que usam bibliotecas, encapsulando funcionalidades úteis.

</div>

---

## Exemplos

- Criar uma função para lançar um dado;
- criar uma função para obter o ano atual;
- criar uma função para calcular uma raiz quadrada.

"""

# Função que usa a biblioteca random

import random

def lancar_dado():
    return random.randint(1, 6)

resultado = lancar_dado()

print("Resultado do dado:", resultado)

# Função que usa a biblioteca datetime

from datetime import datetime

def obter_ano_atual():
    return datetime.now().year

ano = obter_ano_atual()

print("Ano atual:", ano)

import math

def calcular_raiz_quadrada(numero):
    if numero < 0:
        raise ValueError("Não é possível calcular a raiz quadrada de um número negativo.")
    return math.sqrt(numero)

# Exemplo de uso:
try:
  raiz = calcular_raiz_quadrada(81)
  print("Raiz quadrada de 81:", raiz)

  raiz_decimal = calcular_raiz_quadrada(10.24)
  print("Raiz quadrada de 10.24:", raiz_decimal)


  raiz_decimal = calcular_raiz_quadrada(-4)
  print("Raiz quadrada de 10.24:", raiz_decimal)

except ValueError as e:
    print(e)

"""-----------------

# Programa completo num único ficheiro: gestão de notas
"""

# Programa completo num único ficheiro
# Exemplo: gestão simples de notas de alunos


# -----------------------------
# Dados do programa
# -----------------------------

alunos = {
    "Ana": [14, 16, 15],
    "João": [9, 11, 10],
    "Maria": [18, 17, 19],
    "Pedro": [12, 25, 13]
}


# -----------------------------
# Modelo: validações e cálculos
# -----------------------------

def validar_nota(nota):
    if type(nota) != int and type(nota) != float:
        raise TypeError("A nota deve ser um número.")

    if nota < 0 or nota > 20:
        raise ValueError("A nota deve estar entre 0 e 20.")


def validar_lista_notas(notas):
    if type(notas) != list:
        raise TypeError("As notas devem estar numa lista.")

    if len(notas) == 0:
        raise ValueError("A lista de notas não pode estar vazia.")

    for nota in notas:
        validar_nota(nota)


def calcular_media(notas):
    validar_lista_notas(notas)

    soma = 0

    for nota in notas:
        soma = soma + nota

    return soma / len(notas)


def obter_nota_maxima(notas):
    validar_lista_notas(notas)

    maior = notas[0]

    for nota in notas:
        if nota > maior:
            maior = nota

    return maior


def obter_nota_minima(notas):
    validar_lista_notas(notas)

    menor = notas[0]

    for nota in notas:
        if nota < menor:
            menor = nota

    return menor


def classificar_media(media):
    if media >= 16:
        return "Muito bom"
    elif media >= 10:
        return "Aprovado"
    else:
        return "Reprovado"


# -----------------------------
# Vista: apresentação dos dados
# -----------------------------

def mostrar_resultado(nome, media, maxima, minima, classificacao):
    print("Aluno:", nome)
    print("Média:", media)
    print("Nota máxima:", maxima)
    print("Nota mínima:", minima)
    print("Classificação:", classificacao)
    print()


def mostrar_erro(nome, erro):
    print("Erro nos dados do aluno:", nome)
    print("Detalhe:", erro)
    print()


def mostrar_alunos_incluidos_e_excluidos(alunos_incluidos, alunos_excluidos):
    print("Alunos incluídos no cálculo da média final:")

    for aluno in alunos_incluidos:
        print("-", aluno)

    print()

    print("Alunos excluídos do cálculo da média final:")

    if len(alunos_excluidos) == 0:
        print("- Nenhum aluno excluído")
    else:
        for aluno in alunos_excluidos:
            print("-", aluno)

    print()


def mostrar_media_turma(media_turma):
    print("Média final da turma com alunos válidos:", media_turma)


# -----------------------------
# Controlador: execução principal
# -----------------------------

medias_validas = []
alunos_incluidos = []
alunos_excluidos = []

for nome, notas in alunos.items():
    try:
        media = calcular_media(notas)
        maxima = obter_nota_maxima(notas)
        minima = obter_nota_minima(notas)
        classificacao = classificar_media(media)

        medias_validas.append(media)
        alunos_incluidos.append(nome)

        mostrar_resultado(nome, media, maxima, minima, classificacao)

    except TypeError as erro:
        alunos_excluidos.append(nome)
        mostrar_erro(nome, erro)

    except ValueError as erro:
        alunos_excluidos.append(nome)
        mostrar_erro(nome, erro)


# -----------------------------
# Síntese final
# -----------------------------

mostrar_alunos_incluidos_e_excluidos(alunos_incluidos, alunos_excluidos)

if len(medias_validas) > 0:
    media_turma = calcular_media(medias_validas)
    mostrar_media_turma(media_turma)
else:
    print("Não existem alunos válidos para calcular a média final da turma.")

"""# Projecto modular: gestão de notas

Neste notebook vamos transformar um programa único num projecto organizado em vários ficheiros Python.

Para isso, vamos usar uma organização inspirada no padrão de programação **MVC — Modelo, Vista e Controlador**.

O objectivo é separar o código por responsabilidades:

| Ficheiro | Responsabilidade |
|---|---|
| `modelo.py` | Contém as validações, os cálculos e a lógica principal |
| `vista.py` | Contém as funções que mostram informação no ecrã |
| `controlador.py` | Coordena a execução do programa, ligando o modelo à vista |
| `main.py` | É o programa principal, responsável por iniciar a execução |

Esta organização torna o código mais claro, mais fácil de manter e mais fácil de reutilizar.

No final, o notebook executa o programa principal.

## 1. Criar o ficheiro `modelo.py`

Este módulo contém as validações, os cálculos e a classificação.
"""

# Commented out IPython magic to ensure Python compatibility.
# ## eeeree
# %%writefile modelo.py
# # modelo.py
# # Responsável por validações, cálculos e classificação
# 
# 
# def validar_nota(nota):
#     if type(nota) != int and type(nota) != float:
#         raise TypeError("A nota deve ser um número.")
# 
#     if nota < 0 or nota > 20:
#         raise ValueError("A nota deve estar entre 0 e 20.")
# 
# 
# def validar_lista_notas(notas):
#     if type(notas) != list:
#         raise TypeError("As notas devem estar numa lista.")
# 
#     if len(notas) == 0:
#         raise ValueError("A lista de notas não pode estar vazia.")
# 
#     for nota in notas:
#         validar_nota(nota)
# 
# 
# def calcular_media(notas):
#     validar_lista_notas(notas)
# 
#     soma = 0
# 
#     for nota in notas:
#         soma = soma + nota
# 
#     return soma / len(notas)
# 
# 
# def obter_nota_maxima(notas):
#     validar_lista_notas(notas)
# 
#     maior = notas[0]
# 
#     for nota in notas:
#         if nota > maior:
#             maior = nota
# 
#     return maior
# 
# 
# def obter_nota_minima(notas):
#     validar_lista_notas(notas)
# 
#     menor = notas[0]
# 
#     for nota in notas:
#         if nota < menor:
#             menor = nota
# 
#     return menor
# 
# 
# def classificar_media(media):
#     if media >= 16:
#         return "Muito bom"
#     elif media >= 10:
#         return "Aprovado"
#     else:
#         return "Reprovado"
#

"""## 2. Criar o ficheiro `vista.py`

Este módulo contém as funções responsáveis por mostrar informação no ecrã.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile vista.py
# # vista.py
# # Responsável pela apresentação dos resultados
# 
# 
# def mostrar_resultado(nome, media, maxima, minima, classificacao):
#     print("Aluno:", nome)
#     print("Média:", media)
#     print("Nota máxima:", maxima)
#     print("Nota mínima:", minima)
#     print("Classificação:", classificacao)
#     print()
# 
# 
# def mostrar_erro(nome, erro):
#     print("Erro nos dados do aluno:", nome)
#     print("Detalhe:", erro)
#     print()
# 
# 
# def mostrar_alunos_incluidos_e_excluidos(alunos_incluidos, alunos_excluidos):
#     print("Alunos incluídos no cálculo da média final:")
# 
#     for aluno in alunos_incluidos:
#         print("-", aluno)
# 
#     print()
# 
#     print("Alunos excluídos do cálculo da média final:")
# 
#     if len(alunos_excluidos) == 0:
#         print("- Nenhum aluno excluído")
#     else:
#         for aluno in alunos_excluidos:
#             print("-", aluno)
# 
#     print()
# 
# 
# def mostrar_media_turma(media_turma):
#     print("Média final da turma com alunos válidos:", media_turma)
# 
# 
# def mostrar_sem_alunos_validos():
#     print("Não existem alunos válidos para calcular a média final da turma.")
#

"""## 3. Criar o ficheiro `controlador.py`

Este módulo coordena a execução do programa.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile controlador.py
# # controlador.py
# # Responsável por coordenar a execução do programa
# 
# from modelo import calcular_media
# from modelo import obter_nota_maxima
# from modelo import obter_nota_minima
# from modelo import classificar_media
# 
# from vista import mostrar_resultado
# from vista import mostrar_erro
# from vista import mostrar_alunos_incluidos_e_excluidos
# from vista import mostrar_media_turma
# from vista import mostrar_sem_alunos_validos
# 
# 
# def processar_alunos(alunos):
#     medias_validas = []
#     alunos_incluidos = []
#     alunos_excluidos = []
# 
#     for nome, notas in alunos.items():
#         try:
#             media = calcular_media(notas)
#             maxima = obter_nota_maxima(notas)
#             minima = obter_nota_minima(notas)
#             classificacao = classificar_media(media)
# 
#             medias_validas.append(media)
#             alunos_incluidos.append(nome)
# 
#             mostrar_resultado(nome, media, maxima, minima, classificacao)
# 
#         except TypeError as erro:
#             alunos_excluidos.append(nome)
#             mostrar_erro(nome, erro)
# 
#         except ValueError as erro:
#             alunos_excluidos.append(nome)
#             mostrar_erro(nome, erro)
# 
#     mostrar_alunos_incluidos_e_excluidos(alunos_incluidos, alunos_excluidos)
# 
#     if len(medias_validas) > 0:
#         media_turma = calcular_media(medias_validas)
#         mostrar_media_turma(media_turma)
#     else:
#         mostrar_sem_alunos_validos()
#

from controlador import processar_alunos


alunos = {
    "Ana": [14, 16, 15],
    "João": [9, 11, 10],
    "Maria": [18, 17, 19],
    "Pedro": [12, 25, 13]
}


processar_alunos(alunos)

from controlador import processar_alunos


alunos = {
    "Ana": [14, 16, 15],
    "João": [9, 11, 10],
    "Maria": [18, 17, 19],
    "Pedro": [12, 25, 13]
}


processar_alunos(alunos)

"""## 4. Programa principal

Este módulo coordena a execução do programa.
"""

from controlador import processar_alunos


alunos = {
    "Ana": [14, 16, 15],
    "João": [9, 11, 10],
    "Maria": [18, 17, 19],
    "Pedro": [12, 25, 13]
}


processar_alunos(alunos)

"""# 20. Síntese final

---

<div style="background-color:#f1f5f9; padding:15px; border-left:6px solid #2563eb; border-radius:6px;">

### Ideia principal

As funções permitem organizar, reutilizar e tornar o código mais claro. Em Python, podem ser usadas em conjunto com `lambda`, validação de parâmetros e bibliotecas.

</div>

---

## Conceitos principais

| Tema | Ideia essencial |
|---|---|
| **Funções** | Permitem reutilizar código e dividir o programa em partes mais simples |
| **`def`** | Palavra-chave usada para criar funções em Python |
| **Procedimento** | Executa uma ação, normalmente usando `print()` |
| **Função com retorno** | Devolve um valor com `return` |
| **`print()`** | Mostra informação no ecrã |
| **`return`** | Devolve informação ao programa para ser guardada ou reutilizada |
| **Parâmetro** | Nome usado na definição da função |
| **Argumento** | Valor passado quando a função é chamada |
| **Validação** | Verifica se os dados recebidos pela função são adequados |
| **Tratamento simples de erro** | Pode devolver uma mensagem de erro com `return`, embora seja uma abordagem menos profissional |
| **Exceção** | Erro sinalizado durante a execução do programa |
| **`raise`** | Lança uma exceção quando a função deteta um erro |
| **`try` / `except`** | Permite tratar uma exceção de forma controlada no local onde a função é chamada |
| **`TypeError`** | Indica erro no tipo de dado recebido |
| **`ValueError`** | Indica que o tipo está correto, mas o valor é inválido |
| **Objetos imutáveis** | Não são alterados diretamente dentro da função |
| **Objetos mutáveis** | Podem ser alterados dentro da função |
| **`lambda`** | Função curta, anónima e usada para operações simples |
| **`map()`** | Aplica uma função a todos os elementos de uma lista |
| **`filter()`** | Seleciona elementos que cumprem uma condição |
| **Programação funcional** | Estilo em que funções podem ser usadas para transformar ou filtrar dados |
| **Bibliotecas** | Permitem reutilizar código já existente |
| **Importações** | `import`, `from ... import ...` e `as` permitem usar bibliotecas |

---

## Mensagem final

Saber criar funções é uma competência fundamental em Python, porque permite escrever código mais organizado, reutilizável, seguro e fácil de compreender.

Uma boa função não deve apenas executar uma tarefa: deve também receber dados de forma clara, validar os valores recebidos e sinalizar erros de forma adequada quando necessário.
"""